### PR TITLE
Add support for dotbot defaults

### PR DESCRIPTION
**Pull request by oxddr**
Add support for "defaults" part of config, that is applied to all directives. This way one doesn't have to repeat same configuration for every package.

I've formatted the file using black. If that's not something you like, please let me know.

### CODE REVIEW

**Comment by delicb** [comment]
Thanks for the pull request @oxddr . 

I am fine with black formatting. However, I am not sure about using `_context`, since name indicates it is private. Can you point out to dotbot documentation where it is mentioned. 

On the other hand, even if it is private, I am fine with using with a bit of protection (e.g. `hasattr(self, '_context')`, just not to have entire thing blow up if dotbot decides to remove or rename the variable. 

What do you think?

**Comment by oxddr** [comment]
I've used [link plugin](https://github.com/anishathalye/dotbot/blob/master/dotbot/plugins/link.py#L25) as a reference as it was suggested in [dotbot documentation](https://github.com/anishathalye/dotbot#plugins). This context field is defined on the [Plugin class](https://github.com/anishathalye/dotbot/blob/master/dotbot/plugin.py#L10). Since this is abstract class, I think those fields should be treated more like "protected" than private. However I don't have strong preferences about. If you want me to use hasattr, I'm fine with it.

**Comment by delicb** [comment]
I see. Ok, since this is by no means mission critical software, I am willing to take the risk regarding `_context` field and merge this pull request as is. 

Thanks for the contribution, I hope you find the plugin useful.

**Comment by oxddr** [comment]
Yep, this plugin has saved me a lot of time when setting up a new machine! Thanks a lot!

**Pull request merged**
